version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=manchester
      - DB_NAME=towgrow_app
      # Remove these individual Redis env vars
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: node dist/apps/auth-service/main

  redis:
    image: redis:6
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  pgdata:
  redisdata:
