version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=manchester
      - DB_NAME=towgrow_app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAIL_HOST=live.smtp.mailtrap.io
      - MAIL_PORT=587  # Recommended port with STARTTLS
      - MAIL_USER=apismtp@mailtrap.io  # Correct username from credentials
      - MAIL_PASSWORD=8f23c750ff6bc92c1355e5539ae1bfdb
    depends_on:
      - postgres
      - redis
    command: node dist/apps/auth-service/main

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=app_admin
      - POSTGRES_PASSWORD=StrongerPassword123!
      - POSTGRES_DB=towgrow_app
      - POSTGRES_APP_USER=auth_service
      - POSTGRES_APP_PASSWORD=ServicePassword456$
    command: >
      sh -c '
      docker-entrypoint.sh postgres &
      sleep 5
      psql -U app_admin -d towgrow_app -c "CREATE USER $$POSTGRES_APP_USER WITH PASSWORD '$$POSTGRES_APP_PASSWORD';"
      psql -U app_admin -d towgrow_app -c "GRANT CONNECT, TEMPORARY ON DATABASE towgrow_app TO $$POSTGRES_APP_USER;"
      psql -U app_admin -d towgrow_app -c "GRANT USAGE ON SCHEMA public TO $$POSTGRES_APP_USER;"
      wait'
      
  app:
    environment:
      - DB_USER=auth_service  # Changed from postgres
      - DB_PASS=ServicePassword456$
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  pgdata:
  redisdata:
