services:
  - type: web
    name: towgrow-auth
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      # PostgreSQL connection (Neon)
      - key: DB_HOST
        value: ep-cool-heart-a46vowsa-pooler.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASS
        value: npg_1O5EbCwyePXM
      - key: DB_NAME
        value: neondb
        
      # Redis connection (Render)
      - key: REDIS_HOST
        fromService:
          name: towgrow-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: towgrow-redis
          type: redis
          property: port
      - key: REDIS_URL
        fromService:
          name: towgrow-redis
          type: redis
          property: connectionString

  - type: redis
    name: towgrow-redis
    ipAllowList: []
    plan: free