databases:
  - name: towgrow-db
    databaseName: neondb
    user: neon_user
    region: us-east-2
    postgresVersion: 17

  - name: towgrow-redis
    type: redis
    plan: redis-free

services:
  - type: web
    name: towgrow-auth
    envVars:
      # PostgreSQL connection (Neon)
      - key: DB_HOST
        value: ep-cool-heart-a46vowsa-pooler.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASS
        value: npg_1O5EbCwyePXM
      - key: DB_NAME
        value: neondb
        
      # Redis connection (Render)
      - key: REDIS_HOST
        fromService:
          name: towgrow-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: towgrow-redis
          type: redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          name: towgrow-redis
          type: redis
          property: password

  - type: redis
    name: towgrow-redis
    ipAllowList: []
    plan: free  # This should be changed to match Render's plan name
    database: towgrow-db