databases:
  - name: towgrow-db
    databaseName: neondb
    user: neon_user
    region: us-east-2
    postgresVersion: 17

  - name: towgrow-redis
    type: redis
    plan: free
    ipAllowList: []

services:
  - type: web
    name: towgrow-auth
    envVars:
      # PostgreSQL connection
      - key: DB_HOST
        fromDatabase:
          name: towgrow-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        fromDatabase:
          name: towgrow-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: towgrow-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: towgrow-db
          property: database
        
      # Redis connection
      - key: REDIS_HOST
        fromService:
          name: towgrow-redis
          type: redis
          property: host
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        fromService:
          name: towgrow-redis
          type: redis
          property: password