import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsNotEmpty, IsString, IsUUID } from 'class-validator';
import { BiometricType } from './biometric-register.dto';

export class BiometricAuthenticateDto {
  @ApiProperty({
    description: 'User ID to authenticate',
    example: '123e4567-e89b-12d3-a456-426614174000',
    required: true
  })
  @IsNotEmpty({ message: 'User ID is required' })
  @IsUUID()
  userId: string;

  @ApiProperty({
    description: 'Unique identifier for the biometric data (hash or token generated by client)',
    example: 'a1b2c3d4e5f6g7h8i9j0',
    required: true
  })
  @IsNotEmpty({ message: 'Biometric ID is required' })
  @IsString()
  biometricId: string;

  @ApiProperty({
    description: 'Type of biometric method',
    enum: BiometricType,
    example: 'fingerprint',
    required: true
  })
  @IsEnum(BiometricType, { message: 'Type must be either fingerprint or faceId' })
  type: BiometricType;
}