name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      # Using --legacy-peer-deps as a temporary fix until dependencies are properly aligned
      run: npm ci --legacy-peer-deps
      
    - name: Build
      run: npm run build

    # Run tests with coverage
    - name: Run tests
      run: npm run test:cov
      
    # Add E2E tests if needed
    - name: Run E2E tests
      run: npm run test:e2e
      continue-on-error: true

    # Fixed artifact upload configuration
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          coverage/
          test-results.xml

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/v1/services/red-d08c11ngi27c738dr6t0/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY"